In [1]:
import sys
import os

# Get project root (one level above notebooks folder)
project_root = os.path.abspath("E:\DV Data Science\credit-default-forecasting-system")

if project_root not in sys.path:
    sys.path.append(project_root)

print("Added to path:", project_root)

Added to path: E:\DV Data Science\credit-default-forecasting-system

# LOAD THE DATASETS

In [2]:
import pandas as pd
import numpy as np

In [3]:
monthly_default_rate_cleaned=pd.read_csv(r"E:\DV Data Science\credit-default-forecasting-system\data\processed\monthly_default_rate_cleaned.csv")

In [4]:
monthly_default_rate_cleaned["issue_month"]=pd.to_datetime(monthly_default_rate_cleaned["issue_month"])

In [5]:
monthly_default_rate_cleaned=monthly_default_rate_cleaned.set_index("issue_month")

In [6]:
model_comparision=pd.read_csv(r"E:\DV Data Science\credit-default-forecasting-system\data\processed\model_comparison_baselines_arima.csv")

# DO THE WALK FORWARD

In [7]:
from src.evaluation import walk_forward_forecast as wf

In [8]:
from src.models import arima_model as am

In [9]:
actual_wf_arima_100, prediction_wf_arima_100= wf.walk_forward_forecast(monthly_default_rate_cleaned["default_rate"],"2014-12-01",am.arima_train,am.arima_forecast_one_step,model_params={"p":1,"d":0,"q":0})

C:\Anaconda3\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

In [10]:
actual_wf_arima_200, prediction_wf_arima_200= wf.walk_forward_forecast(monthly_default_rate_cleaned["default_rate"],"2014-12-01",am.arima_train,am.arima_forecast_one_step,model_params={"p":2,"d":0,"q":0})

C:\Anaconda3\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

In [11]:
actual_wf_arima_101, prediction_wf_arima_101= wf.walk_forward_forecast(monthly_default_rate_cleaned["default_rate"],"2014-12-01",am.arima_train,am.arima_forecast_one_step,model_params={"p":1,"d":0,"q":1})

In [12]:
actual_wf_arima_201, prediction_wf_arima_201= wf.walk_forward_forecast(monthly_default_rate_cleaned["default_rate"],"2014-12-01",am.arima_train,am.arima_forecast_one_step,model_params={"p":2,"d":0,"q":1})

C:\Anaconda3\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Anaconda3\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Anaconda3\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Anaconda3\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Anaconda3\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Anaconda3\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Anaconda3\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Anaconda3\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

# EVALUATE THE MODELS

In [13]:
from src.evaluation import metrics as mt

In [14]:
arima_100_metrics=list(mt.evaluate_model(actual_wf_arima_100, prediction_wf_arima_100))

D TYPE OF issue_month
2014-12-01    0.166974
2015-01-01    0.183297
2015-02-01    0.176273
2015-03-01    0.187323
2015-04-01    0.183024
2015-05-01    0.183154
2015-06-01    0.184799
2015-07-01    0.179692
2015-08-01    0.175082
2015-09-01    0.179393
2015-10-01    0.167136
2015-11-01    0.172102
2015-12-01    0.181133
2016-01-01    0.166625
2016-02-01    0.167649
2016-03-01    0.168248
2016-04-01    0.166118
2016-05-01    0.164173
2016-06-01    0.149732
2016-07-01    0.162209
2016-08-01    0.156340
2016-09-01    0.145075
2016-10-01    0.125168
2016-11-01    0.128213
2016-12-01    0.128513
Name: default_rate, dtype: float64: float64
D TYPE OF issue_month
2014-12-01    0.166167
2015-01-01    0.166178
2015-02-01    0.178332
2015-03-01    0.173151
2015-04-01    0.181421
2015-05-01    0.178298
2015-06-01    0.178451
2015-07-01    0.179736
2015-08-01    0.175972
2015-09-01    0.172567
2015-10-01    0.175810
2015-11-01    0.166693
2015-12-01    0.170403
2016-01-01    0.177162
2016-02-01    0.166368
2016-03-01    0.167131
2016-04-01    0.167584
2016-05-01    0.166001
2016-06-01    0.164553
2016-07-01    0.153776
2016-08-01    0.163052
2016-09-01    0.158672
2016-10-01    0.150287
2016-11-01    0.135203
2016-12-01    0.137329
dtype: float64: float64

In [15]:
model_comparision

,Unnamed: 0,NAIVE,MA3,MA6,"ARIMA(1,0,0)","ARIMA(2,0,0)","ARIMA(1,0,1)","ARIMA(2,0,1)"
0,RMSE,0.008974,0.009251,0.011536,0.017849,0.017352,0.017403,0.017516
1,MAE,0.007011,0.006503,0.008902,0.014261,0.013882,0.013819,0.014173
2,MAPE,0.043621,0.042823,0.059066,0.091761,0.089415,0.089200,0.090930

In [16]:
model_comparision=model_comparision.set_index("Unnamed: 0")
model_comparision

,NAIVE,MA3,MA6,"ARIMA(1,0,0)","ARIMA(2,0,0)","ARIMA(1,0,1)","ARIMA(2,0,1)"
Unnamed: 0,,,,,,,
RMSE,0.008974,0.009251,0.011536,0.017849,0.017352,0.017403,0.017516
MAE,0.007011,0.006503,0.008902,0.014261,0.013882,0.013819,0.014173
MAPE,0.043621,0.042823,0.059066,0.091761,0.089415,0.089200,0.090930

In [17]:
model_comparision["ARIMA(1,0,0) WALK FORWARD"]=pd.Series(arima_100_metrics,index=model_comparision.index)

In [18]:
model_comparision

,NAIVE,MA3,MA6,"ARIMA(1,0,0)","ARIMA(2,0,0)","ARIMA(1,0,1)","ARIMA(2,0,1)","ARIMA(1,0,0) WALK FORWARD"
Unnamed: 0,,,,,,,,
RMSE,0.008974,0.009251,0.011536,0.017849,0.017352,0.017403,0.017516,0.009444
MAE,0.007011,0.006503,0.008902,0.014261,0.013882,0.013819,0.014173,0.007210
MAPE,0.043621,0.042823,0.059066,0.091761,0.089415,0.089200,0.090930,0.046002

In [19]:
arima_200_metrics=list(mt.evaluate_model(actual_wf_arima_200, prediction_wf_arima_200))

D TYPE OF issue_month
2014-12-01    0.166974
2015-01-01    0.183297
2015-02-01    0.176273
2015-03-01    0.187323
2015-04-01    0.183024
2015-05-01    0.183154
2015-06-01    0.184799
2015-07-01    0.179692
2015-08-01    0.175082
2015-09-01    0.179393
2015-10-01    0.167136
2015-11-01    0.172102
2015-12-01    0.181133
2016-01-01    0.166625
2016-02-01    0.167649
2016-03-01    0.168248
2016-04-01    0.166118
2016-05-01    0.164173
2016-06-01    0.149732
2016-07-01    0.162209
2016-08-01    0.156340
2016-09-01    0.145075
2016-10-01    0.125168
2016-11-01    0.128213
2016-12-01    0.128513
Name: default_rate, dtype: float64: float64
D TYPE OF issue_month
2014-12-01    0.168048
2015-01-01    0.166166
2015-02-01    0.175742
2015-03-01    0.175206
2015-04-01    0.179998
2015-05-01    0.179984
2015-06-01    0.179325
2015-07-01    0.180367
2015-08-01    0.177771
2015-09-01    0.173972
2015-10-01    0.175517
2015-11-01    0.169300
2015-12-01    0.169522
2016-01-01    0.175893
2016-02-01    0.169440
2016-03-01    0.166848
2016-04-01    0.167430
2016-05-01    0.166320
2016-06-01    0.164716
2016-07-01    0.155833
2016-08-01    0.159931
2016-09-01    0.159251
2016-10-01    0.151343
2016-11-01    0.137024
2016-12-01    0.134330
dtype: float64: float64

In [20]:
model_comparision["ARIMA(2,0,0) WALK FORWARD"]=pd.Series(arima_200_metrics,index=model_comparision.index)
model_comparision

,NAIVE,MA3,MA6,"ARIMA(1,0,0)","ARIMA(2,0,0)","ARIMA(1,0,1)","ARIMA(2,0,1)","ARIMA(1,0,0) WALK FORWARD","ARIMA(2,0,0) WALK FORWARD"
Unnamed: 0,,,,,,,,,
RMSE,0.008974,0.009251,0.011536,0.017849,0.017352,0.017403,0.017516,0.009444,0.009195
MAE,0.007011,0.006503,0.008902,0.014261,0.013882,0.013819,0.014173,0.007210,0.006798
MAPE,0.043621,0.042823,0.059066,0.091761,0.089415,0.089200,0.090930,0.046002,0.043588

In [21]:
arima_101_metrics=list(mt.evaluate_model(actual_wf_arima_101, prediction_wf_arima_101))

D TYPE OF issue_month
2014-12-01    0.166974
2015-01-01    0.183297
2015-02-01    0.176273
2015-03-01    0.187323
2015-04-01    0.183024
2015-05-01    0.183154
2015-06-01    0.184799
2015-07-01    0.179692
2015-08-01    0.175082
2015-09-01    0.179393
2015-10-01    0.167136
2015-11-01    0.172102
2015-12-01    0.181133
2016-01-01    0.166625
2016-02-01    0.167649
2016-03-01    0.168248
2016-04-01    0.166118
2016-05-01    0.164173
2016-06-01    0.149732
2016-07-01    0.162209
2016-08-01    0.156340
2016-09-01    0.145075
2016-10-01    0.125168
2016-11-01    0.128213
2016-12-01    0.128513
Name: default_rate, dtype: float64: float64
D TYPE OF issue_month
2014-12-01    0.167787
2015-01-01    0.166538
2015-02-01    0.176636
2015-03-01    0.174267
2015-04-01    0.180828
2015-05-01    0.179477
2015-06-01    0.179322
2015-07-01    0.180377
2015-08-01    0.177375
2015-09-01    0.173861
2015-10-01    0.175895
2015-11-01    0.168558
2015-12-01    0.170211
2016-01-01    0.176283
2016-02-01    0.168367
2016-03-01    0.167386
2016-04-01    0.167565
2016-05-01    0.166261
2016-06-01    0.164763
2016-07-01    0.155312
2016-08-01    0.161242
2016-09-01    0.158751
2016-10-01    0.151093
2016-11-01    0.136736
2016-12-01    0.135624
dtype: float64: float64

In [22]:
model_comparision["ARIMA(1,0,1) WALK FORWARD"]=pd.Series(arima_101_metrics,index=model_comparision.index)
model_comparision

,NAIVE,MA3,MA6,"ARIMA(1,0,0)","ARIMA(2,0,0)","ARIMA(1,0,1)","ARIMA(2,0,1)","ARIMA(1,0,0) WALK FORWARD","ARIMA(2,0,0) WALK FORWARD","ARIMA(1,0,1) WALK FORWARD"
Unnamed: 0,,,,,,,,,,
RMSE,0.008974,0.009251,0.011536,0.017849,0.017352,0.017403,0.017516,0.009444,0.009195,0.009222
MAE,0.007011,0.006503,0.008902,0.014261,0.013882,0.013819,0.014173,0.007210,0.006798,0.006837
MAPE,0.043621,0.042823,0.059066,0.091761,0.089415,0.089200,0.090930,0.046002,0.043588,0.043883

In [23]:
arima_201_metrics=list(mt.evaluate_model(actual_wf_arima_201, prediction_wf_arima_201))

D TYPE OF issue_month
2014-12-01    0.166974
2015-01-01    0.183297
2015-02-01    0.176273
2015-03-01    0.187323
2015-04-01    0.183024
2015-05-01    0.183154
2015-06-01    0.184799
2015-07-01    0.179692
2015-08-01    0.175082
2015-09-01    0.179393
2015-10-01    0.167136
2015-11-01    0.172102
2015-12-01    0.181133
2016-01-01    0.166625
2016-02-01    0.167649
2016-03-01    0.168248
2016-04-01    0.166118
2016-05-01    0.164173
2016-06-01    0.149732
2016-07-01    0.162209
2016-08-01    0.156340
2016-09-01    0.145075
2016-10-01    0.125168
2016-11-01    0.128213
2016-12-01    0.128513
Name: default_rate, dtype: float64: float64
D TYPE OF issue_month
2014-12-01    0.167283
2015-01-01    0.165725
2015-02-01    0.175940
2015-03-01    0.176019
2015-04-01    0.179394
2015-05-01    0.180915
2015-06-01    0.178601
2015-07-01    0.180440
2015-08-01    0.177631
2015-09-01    0.173470
2015-10-01    0.175272
2015-11-01    0.169422
2015-12-01    0.168612
2016-01-01    0.176523
2016-02-01    0.169591
2016-03-01    0.165773
2016-04-01    0.167768
2016-05-01    0.166172
2016-06-01    0.164549
2016-07-01    0.155592
2016-08-01    0.159194
2016-09-01    0.160244
2016-10-01    0.150594
2016-11-01    0.136415
2016-12-01    0.133401
dtype: float64: float64

In [24]:
model_comparision["ARIMA(2,0,1) WALK FORWARD"]=pd.Series(arima_201_metrics,index=model_comparision.index)
model_comparision

,NAIVE,MA3,MA6,"ARIMA(1,0,0)","ARIMA(2,0,0)","ARIMA(1,0,1)","ARIMA(2,0,1)","ARIMA(1,0,0) WALK FORWARD","ARIMA(2,0,0) WALK FORWARD","ARIMA(1,0,1) WALK FORWARD","ARIMA(2,0,1) WALK FORWARD"
Unnamed: 0,,,,,,,,,,,
RMSE,0.008974,0.009251,0.011536,0.017849,0.017352,0.017403,0.017516,0.009444,0.009195,0.009222,0.009208
MAE,0.007011,0.006503,0.008902,0.014261,0.013882,0.013819,0.014173,0.007210,0.006798,0.006837,0.006803
MAPE,0.043621,0.042823,0.059066,0.091761,0.089415,0.089200,0.090930,0.046002,0.043588,0.043883,0.043447

In [25]:
model_comparision.to_csv(r"E:\DV Data Science\credit-default-forecasting-system\data\processed\model_comparision_wf.csv")

PermissionError: [Errno 13] Permission denied: 'E:\\DV Data Science\\credit-default-forecasting-system\\data\\processed\\model_comparision_wf.csv'

# PLOT ACTUAL VS ARIMA(2,0,0)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot(actual_wf_arima_201.index,actual_wf_arima_201,color='blue')
plt.plot(actual_wf_arima_201.index,prediction_wf_arima_201,color='orange')
plt.title("ACTUAL V/S ARIMA(2,0,0)")
plt.savefig(r"E:\DV Data Science\credit-default-forecasting-system\reports\figures\ARIMA_200_wf_VS_ACTUAL.png",dpi=300, bbox_inches="tight")
plt.show()

Walk-forward backtesting was conducted to simulate realistic forecasting conditions. Among ARIMA specifications tested, ARIMA(2,0,0) achieved the best performance. However, baseline models such as the naive forecast remained highly competitive, indicating strong persistence in the default rate series.